(()=>{
const $=s=>document.querySelector(s), DAY_KEY='archive-reading-days-v1', PLATFORM_KEY='archive-platform-v1';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const css=document.createElement('style');css.textContent=`
.archive-rituals{margin:24px 0 30px;display:grid;gap:14px}.ritual-card{border:1px solid #4d3b2f;background:linear-gradient(145deg,#1b1410,#100c0a);border-radius:24px;padding:20px;color:#eadfce}.ritual-card small{color:#d2aa6d;letter-spacing:.17em}.ritual-card h2{font-family:'Cormorant Garamond',Georgia,serif;font-size:31px;margin:6px 0 10px}.ritual-card p{color:#a99b8d;line-height:1.55}.ritual-head{display:flex;align-items:center;justify-content:space-between;gap:12px}.streak-orb{min-width:72px;height:72px;border:1px solid #765b40;border-radius:50%;display:grid;place-items:center;text-align:center;background:#ffffff05}.streak-orb b{font-family:Georgia,serif;font-size:25px;color:#e1bb7c;line-height:1}.streak-orb span{font-size:9px;color:#9e8e80;text-transform:uppercase;letter-spacing:.12em}.week-strip{display:grid;grid-template-columns:repeat(7,1fr);gap:6px;margin-top:15px}.day-dot{border:1px solid #3e3027;border-radius:13px;padding:9px 3px;text-align:center;color:#71655b;font-size:10px}.day-dot b{display:block;font-size:13px;margin-top:3px}.day-dot.read{background:#d0aa6b;color:#21170f;border-color:#d0aa6b}.day-dot.today{box-shadow:inset 0 0 0 1px #f0dbc0}.recent-row{display:flex;gap:11px;overflow:auto;scrollbar-width:none;padding-bottom:3px}.recent-row::-webkit-scrollbar{display:none}.recent-book{width:118px;flex:none;cursor:pointer}.recent-book img,.recent-fallback{width:100%;aspect-ratio:.68;object-fit:cover;border-radius:10px;border:1px solid #574334;background:#211914}.recent-book b{display:block;font-family:'Cormorant Garamond';font-size:16px;margin-top:6px;line-height:1.05}.recent-book span{font-size:9px;color:#8e8074}.ritual-action{border:1px solid #66503b;background:#eadfcf;color:#21170f;padding:11px 15px;border-radius:999px;font-weight:800;margin-top:8px}.mood-row{display:flex;gap:7px;overflow:auto;padding:4px 0;scrollbar-width:none}.mood-row button{flex:none;border:1px solid #4e3d31;background:#17110e;color:#b5a596;border-radius:999px;padding:9px 12px;font-weight:700}.mood-row button.active{background:#d8b777;color:#20150e;border-color:#d8b777}.mood-result{margin-top:12px;padding:13px;border-left:2px solid #b78f59;background:#ffffff05;border-radius:0 14px 14px 0;cursor:pointer}.mood-result b{display:block;font-family:'Cormorant Garamond';font-size:21px}.mood-result span{font-size:10px;color:#98897b}@media(max-width:520px){.ritual-card{padding:17px}.streak-orb{min-width:64px;height:64px}}
`;document.head.appendChild(css);
function dayString(d=new Date()){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function getDays(){try{return JSON.parse(localStorage.getItem(DAY_KEY)||'[]')}catch{return[]}}
function saveDays(a){localStorage.setItem(DAY_KEY,JSON.stringify([...new Set(a)].slice(-400)))}
function markToday(){const a=getDays(),t=dayString();if(!a.includes(t)){a.push(t);saveDays(a);renderStreak()}}
function streak(){const set=new Set(getDays());let n=0,d=new Date();while(set.has(dayString(d))){n++;d.setDate(d.getDate()-1)}if(n===0){d=new Date();d.setDate(d.getDate()-1);while(set.has(dayString(d))){n++;d.setDate(d.getDate()-1)}}return n}
function platform(){try{return JSON.parse(localStorage.getItem(PLATFORM_KEY)||'{}')}catch{return{}}}
function wait(){if(typeof books==='undefined'||!document.querySelector('main'))return setTimeout(wait,80);install()}
function install(){const main=document.querySelector('main'),anchor=document.querySelector('.stats');const wrap=document.createElement('section');wrap.className='archive-rituals';wrap.innerHTML=`<div class="ritual-card"><div class="ritual-head"><div><small>READING RITUAL</small><h2 id="ritualTitle">Tonight belongs to a book.</h2><p id="ritualCopy"></p></div><div class="streak-orb"><div><b id="streakNum">0</b><span>day streak</span></div></div></div><div class="week-strip" id="weekStrip"></div><button class="ritual-action" id="ritualOpen">Choose tonight's book →</button></div><div class="ritual-card"><small>RECENTLY READ</small><h2>Pick up where you vanished.</h2><div class="recent-row" id="recentRow"></div></div><div class="ritual-card"><small>READ BY MOOD</small><h2>What kind of mistake are we making?</h2><div class="mood-row" id="moodRow"><button data-mood="haunted">Haunted</button><button data-mood="romantic">Obsessed</button><button data-mood="strange">Strange</button><button data-mood="magic">Magical</button><button data-mood="quick">Just one chapter</button></div><div id="moodResult"></div></div>`;anchor?main.insertBefore(wrap,anchor):main.appendChild(wrap);
 const rituals=[['One chapter. No notifications.','Put the phone on Do Not Disturb and give one chapter your full attention.'],['Read until the room disappears.','Ten quiet minutes count. Accidentally reading for an hour also counts.'],['A tiny literary disappearance.','Pick something you have not opened recently and read one complete scene.'],['Return to the unfinished door.','Continue the book with the most progress that is not finished yet.'],['Tonight: terrible fictional decisions.','The Archive recommends choosing entirely by cover and accepting the consequences.']];const r=rituals[(new Date().getDate()+new Date().getMonth())%rituals.length];$('#ritualTitle').textContent=r[0];$('#ritualCopy').textContent=r[1];
 $('#ritualOpen').onclick=()=>{const p=platform(),hist=p.history||[];let b=hist.length?books.find(x=>x.id===hist[0].id):books.find(x=>(x.progress||0)>0&&(x.progress||0)<100);if(!b)b=books[Math.floor(Math.random()*books.length)];if(b&&typeof openDetail==='function')openDetail(b.id)};
 $('#moodRow').onclick=e=>{const btn=e.target.closest('[data-mood]');if(!btn)return;$('#moodRow').querySelectorAll('button').forEach(x=>x.classList.toggle('active',x===btn));showMood(btn.dataset.mood)};
 renderStreak();renderRecent();setInterval(()=>{const reader=document.querySelector('#reader');if(reader&&!reader.classList.contains('hidden')&&!document.hidden)markToday()},5000);window.addEventListener('focus',()=>{renderStreak();renderRecent()});}
function renderStreak(){const n=$('#streakNum');if(!n)return;n.textContent=streak();const days=new Set(getDays()),today=new Date(),items=[];for(let i=6;i>=0;i--){const d=new Date(today);d.setDate(today.getDate()-i);const k=dayString(d);items.push(`<div class="day-dot ${days.has(k)?'read':''} ${i===0?'today':''}">${d.toLocaleDateString(undefined,{weekday:'short'}).slice(0,2)}<b>${d.getDate()}</b></div>`)}$('#weekStrip').innerHTML=items.join('')}
function renderRecent(){const row=$('#recentRow');if(!row||typeof books==='undefined')return;const p=platform(),seen=new Set(),arr=[];(p.history||[]).forEach(h=>{if(seen.has(h.id))return;const b=books.find(x=>x.id===h.id);if(b){seen.add(h.id);arr.push(b)}});books.filter(b=>(b.progress||0)>0&&!seen.has(b.id)).sort((a,b)=>(b.progress||0)-(a.progress||0)).forEach(b=>arr.push(b));row.innerHTML=arr.slice(0,8).map(b=>`<div class="recent-book" data-id="${esc(b.id)}">${b.cover?`<img src="${b.cover}" alt="">`:`<div class="recent-fallback"></div>`}<b>${esc(b.title)}</b><span>${b.progress||0}% read</span></div>`).join('')||'<p style="color:#88796c">Nothing yet. Open a book and make this section useful ♡</p>';row.querySelectorAll('[data-id]').forEach(x=>x.onclick=()=>typeof openDetail==='function'&&openDetail(x.dataset.id))}
function showMood(mood){if(typeof books==='undefined')return;const text=b=>`${b.title} ${b.fandom||''} ${(b.tags||[]).join(' ')} ${b.summary||''}`.toLowerCase();const tests={haunted:/horror|haunt|ghost|dead|gothic|liminal|uncanny/,romantic:/romance|love|obsess|slow burn|vampire/,strange:/mystery|liminal|surreal|time|memory|museum|uncanny/,magic:/fantasy|magic|witch|kingdom|crown|myth/,quick:/.*/};let pool=books.filter(tests[mood]);if(mood==='quick')pool=[...books].sort((a,b)=>(a.words||0)-(b.words||0)).slice(0,5);const b=pool[Math.floor(Math.random()*pool.length)];const out=$('#moodResult');if(!b){out.innerHTML='<p>No matching book yet. Which is clearly a reason to write another one.</p>';return}out.innerHTML=`<div class="mood-result" data-id="${esc(b.id)}"><b>${esc(b.title)}</b><span>${esc(b.fandom||'Original')} · ${(b.words||0).toLocaleString()} words · ${b.progress||0}% read</span></div>`;out.querySelector('[data-id]').onclick=()=>typeof openDetail==='function'&&openDetail(b.id)}
wait();
})();