/* THE ARCHIVE 3.0 — consolidated runtime */
'use strict';
var books=[];
var selected=null;
var chapter=0;
var filter='all';
const shelf=document.querySelector('#shelf');
const readerEl=document.querySelector('#reader');
const LIBRARY_KEY='archive-books';
const READING_KEY='archive-reading-stats-v2';
const MEGA_KEY='archive-mega-v2';
const DAYS_KEY='archive-reading-days-v2';
const OFFICIAL_ID='door-radiator';
const FANFIC_ID='veil-of-forks';
const MANUSCRIPT='The door behind the radiator .txt';
const FANFIC_MANUSCRIPT='twilight-dark-fanfic.txt';
const COVER='thedoorbehindtheradiator.PNG';
const FANFIC_COVER='veil-of-forks-cover.svg';
const $=(s,r=document)=>r.querySelector(s);
const $$=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const wc=s=>String(s||'').trim()?String(s).trim().split(/\s+/).length:0;
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
function safeJSON(key,fallback){try{const v=JSON.parse(localStorage.getItem(key)||'null');return v??fallback}catch{return fallback}}
function num(v,d=0){v=Number(v);return Number.isFinite(v)&&v>=0?v:d}
function arr(v){return Array.isArray(v)?v:[]}
function obj(v){return v&&typeof v==='object'&&!Array.isArray(v)?v:{}}
let readingData=(()=>{const r=obj(safeJSON(READING_KEY,obj(safeJSON('archive-reading-stats-v1',{}))));return{seconds:num(r.seconds),opened:obj(r.opened),books:obj(r.books)}})();
let state=(()=>{const s=obj(safeJSON(MEGA_KEY,obj(safeJSON('archive-mega-v1',{}))));return{genre:typeof s.genre==='string'?s.genre:'All',sort:['default','title','short','long','progress','rating'].includes(s.sort)?s.sort:'default',unread:!!s.unread,minWords:num(s.minWords),ratings:obj(s.ratings),notes:obj(s.notes),shelves:obj(s.shelves),quotes:arr(s.quotes).slice(0,200),history:arr(s.history).slice(0,200),goal:Math.max(1000,Math.round(num(s.goal,100000))),prefs:{theme:['paper','sepia','midnight'].includes(s.prefs?.theme)?s.prefs.theme:'paper',font:['serif','garamond','sans'].includes(s.prefs?.font)?s.prefs.font:'serif',size:clamp(num(s.prefs?.size,18),15,27)},bookmarks:obj(s.bookmarks)}})();
function saveState(){try{localStorage.setItem(MEGA_KEY,JSON.stringify(state))}catch(e){console.warn('Archive state save failed',e)}}
function saveReadingData(){try{localStorage.setItem(READING_KEY,JSON.stringify(readingData))}catch(e){console.warn('Reading stats save failed',e)}}
function persist(){const lightweight=books.map(b=>{if(b.librarianV2)return{id:b.id,shelf:b.shelf,favorite:!!b.favorite,progress:num(b.progress),lastChapter:num(b.lastChapter)};if(b.official||b.original||b.fanfic)return{id:b.id,shelf:b.shelf,favorite:!!b.favorite,progress:num(b.progress),lastChapter:num(b.lastChapter)};return b});try{localStorage.setItem(LIBRARY_KEY,JSON.stringify(lightweight))}catch(e){console.warn('Library save failed',e)}}
function savedState(){const v=safeJSON(LIBRARY_KEY,[]);return Array.isArray(v)?v:[]}
function trackerFor(book){let t=obj(readingData.books[book.id]);t.chapters=obj(t.chapters);readingData.books[book.id]=t;return t}
function actualWords(book){return arr(book.chapters).reduce((n,c)=>n+wc(c?.[1]),0)}
function wordsReadFor(book){const t=obj(readingData.books[book.id]);const ch=obj(t.chapters);const total=arr(book.chapters).reduce((sum,c,i)=>sum+Math.round(wc(c?.[1])*clamp(num(ch[i]),0,1)),0);return Math.min(actualWords(book)||Infinity,total)}
function syncBookProgress(book){const total=actualWords(book)||num(book.words)||1;book.words=total;book.progress=clamp(Math.round(wordsReadFor(book)/total*100),0,100);if(book.progress>=100)book.shelf='finished';else if(readingData.opened[book.id])book.shelf='reading';else if(!['tbr','reading','finished'].includes(book.shelf))book.shelf='tbr'}
function syncAllProgress(){books.forEach(syncBookProgress)}
function chapterCountRead(){return books.reduce((n,b)=>{const ch=obj(readingData.books[b.id]?.chapters);return n+Object.values(ch).filter(v=>num(v)>=.985).length},0)}
function totalWordsRead(){return books.reduce((n,b)=>n+wordsReadFor(b),0)}
function formatTime(s){const m=Math.floor(num(s)/60);return m<60?`${m}m`:`${Math.floor(m/60)}h ${String(m%60).padStart(2,'0')}m`}
function dayKey(d=new Date()){return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function readingDays(){const d=safeJSON(DAYS_KEY,[]);return Array.isArray(d)?d:[]}
function markToday(){const a=readingDays(),k=dayKey();if(!a.includes(k)){a.push(k);try{localStorage.setItem(DAYS_KEY,JSON.stringify(a.slice(-500)))}catch{}}}
function streak(){const set=new Set(readingDays());let n=0,d=new Date();while(set.has(dayKey(d))){n++;d.setDate(d.getDate()-1)}return n}
function parseManuscript(raw){const clean=String(raw||'').replace(/\r/g,'').replace(/\u2028|\u2029/g,'\n');const re=/^(Chapter\s+\d+\s*[–—-]\s*.+|Extra\s*[–—-]\s*.+)$/gmi;const m=[...clean.matchAll(re)];return m.map((x,i)=>[x[0].trim(),clean.slice(x.index+x[0].length,i+1<m.length?m[i+1].index:clean.length).trim()]).filter(c=>c[1])}
function parseFanfic(raw){const clean=String(raw||'').replace(/\r/g,'');const re=/^(CHAPTER\s+\d+\s*[–—-]\s*.+|EPILOGUE\s*[–—-]\s*.+)$/gmi;const m=[...clean.matchAll(re)];return m.map((x,i)=>[x[0].replace(/^CHAPTER\s+\d+\s*[–—-]\s*/i,'').replace(/^EPILOGUE\s*[–—-]\s*/i,'Epilogue — '),clean.slice(x.index+x[0].length,i+1<m.length?m[i+1].index:clean.length).trim()]).filter(c=>c[1])}
async function loadText(path){try{const r=await fetch(encodeURI(path));if(!r.ok)throw new Error(`${r.status}`);return await r.text()}catch(e){console.error('Could not load',path,e);return''}}
async function loadOfficialBook(){const raw=await loadText(MANUSCRIPT),chapters=parseManuscript(raw);return{id:OFFICIAL_ID,title:'The Door Behind the Radiator',author:'Marie Dudek',fandom:'Original Horror',genre:'Horror',tags:['Psychological horror','Other world','Winter','Uncanny','Dark fantasy'],summary:'Fifteen-year-old Michael Petrov hears something whispering through the radiator in his Saint Petersburg apartment. Behind it waits a tiny door, an impossible copy of home, and a world offering warmth, safety and love at a price he cannot afford to pay.',status:chapters.length?'Complete':'Unavailable',shelf:'tbr',favorite:false,progress:0,lastChapter:0,cover:COVER,official:true,chapters:chapters.length?chapters:[['Manuscript unavailable','The manuscript could not be loaded. Refresh and try again.']]}}
async function loadFanfic(){const raw=await loadText(FANFIC_MANUSCRIPT);let chapters=parseFanfic(raw);if(typeof window.expandVeilChapters==='function'&&chapters.length===40)chapters=window.expandVeilChapters(chapters);return{id:FANFIC_ID,title:'Veil of Forks',author:'Elias',fandom:'Twilight · Alternate Universe',genre:'Fanfic',tags:['Edward Cullen','Marie','Obsessive Edward','Slow burn','Vampires','Forks','Alternate universe'],summary:'Bella Swan never came to Forks. Marie did. Edward Cullen cannot hear her thoughts and becomes fascinated with the one person who refuses to orbit him.',status:chapters.length?`Complete · ${chapters.length} chapters`:'Unavailable',shelf:'tbr',favorite:false,progress:0,lastChapter:0,cover:FANFIC_COVER,official:true,fanfic:true,chapters:chapters.length?chapters:[['Story unavailable','The story file could not be loaded. Refresh and try again.']]}}
function mergeSaved(fresh){const saved=savedState(),prior=new Map(saved.map(x=>[String(x.id),x]));return fresh.map(b=>{const p=prior.get(String(b.id));return p?{...b,shelf:p.shelf||b.shelf,favorite:!!p.favorite,progress:num(p.progress),lastChapter:num(p.lastChapter)}:b})}
function getAllBuiltIns(){const out=[];if(typeof window.buildArchiveOriginals==='function')out.push(...window.buildArchiveOriginals());if(typeof window.buildArchiveOriginalsVol2==='function')out.push(...window.buildArchiveOriginalsVol2());return out}
function searchText(b){return`${b.title||''} ${b.author||''} ${b.fandom||''} ${b.genre||''} ${(b.tags||[]).join(' ')} ${b.summary||''}`.toLowerCase()}
const GENRES={All:()=>true,Horror:b=>/horror|haunt|ghost|uncanny|liminal|nightmare|dread|radiator|drowned/.test(searchText(b)),'Dark Romance':b=>/dark romance|romance|slow burn|obsess|possessive|forbidden|enemies to|lover/.test(searchText(b)),Fantasy:b=>/fantasy|magic|royal|witch|crown|cathedral|spell|myth|folklore/.test(searchText(b)),'Sci-Fi':b=>/sci-fi|science fiction|cyber|space|time travel|future|orbit|technology/.test(searchText(b)),Mystery:b=>/mystery|murder|investig|detective|secret|case|missing/.test(searchText(b)),Vampires:b=>/vampire|cullen|twilight|volturi|forks/.test(searchText(b)),Gothic:b=>/gothic|cathedral|garden|manor|house|velvet|blackwood/.test(searchText(b)),Fanfic:b=>!!b.fanfic||/fanfic|fanfiction|twilight/.test(searchText(b))};
function filteredBooks(){let a=books.filter(GENRES[state.genre]||GENRES.All);const q=($('#search')?.value||'').trim().toLowerCase();if(q)a=a.filter(b=>searchText(b).includes(q));if(filter!=='all')a=a.filter(b=>filter==='favorite'?b.favorite:b.shelf===filter);if(state.unread)a=a.filter(b=>(b.progress||0)<100);if(state.minWords)a=a.filter(b=>(b.words||0)>=state.minWords);const rating=id=>num(state.ratings[id]);return[...a].sort((x,y)=>state.sort==='title'?x.title.localeCompare(y.title):state.sort==='short'?(x.words||0)-(y.words||0):state.sort==='long'?(y.words||0)-(x.words||0):state.sort==='progress'?(y.progress||0)-(x.progress||0):state.sort==='rating'?rating(y.id)-rating(x.id):0)}
function coverMarkup(b){return b.cover?`<img class="real-cover" src="${esc(b.cover)}" alt="Cover of ${esc(b.title)}">`:`<span>${esc(b.title)}</span><i>${b.favorite?'♡':'✦'}</i>`}
function render(){syncAllProgress();const a=filteredBooks();shelf.innerHTML=a.map(b=>`<div class="book-card ${b.official?'official-book':''}" data-id="${esc(b.id)}"><div class="book">${coverMarkup(b)}</div><b>${esc(b.title)}</b><small>${esc(b.author||'')}</small><div class="progressbar"><i style="width:${clamp(num(b.progress),0,100)}%"></i></div>${state.ratings[b.id]||state.shelves[b.id]?`<div class="v3-badges">${state.ratings[b.id]?`<span>${'★'.repeat(clamp(num(state.ratings[b.id]),0,5))}</span>`:''}${state.shelves[b.id]?`<span>${esc(state.shelves[b.id])}</span>`:''}</div>`:''}</div>`).join('')||'<div class="v3-empty">Nothing on this shelf.</div>';$('#count').textContent=`${a.length} title${a.length===1?'':'s'}`;const heading=$('.section-title h2');if(heading)heading.textContent=filter==='all'?'Library':filter==='favorite'?'Favorites':filter[0].toUpperCase()+filter.slice(1);$$('.book-card',shelf).forEach(c=>c.onclick=()=>openDetail(c.dataset.id));updateStats();refreshDashboard()}
function renderMega(){render()}
function updateStats(){const x=[['#booksOpenedCount',Object.keys(readingData.opened).filter(id=>books.some(b=>String(b.id)===String(id))).length],['#chaptersReadCount',chapterCountRead().toLocaleString()],['#readingTime',formatTime(readingData.seconds)],['#wordCount',totalWordsRead().toLocaleString()]];x.forEach(([s,v])=>{const e=$(s);if(e)e.textContent=v})}
function setupFeatured(){const b=books.find(x=>x.id===FANFIC_ID)||books.find(x=>x.id===OFFICIAL_ID)||books[0];if(!b)return;$('#heroTitle').textContent=b.title;$('.hero-copy p').textContent=`${b.fandom} · ${(b.words||0).toLocaleString()} words · ${b.progress||0}% read`;const hb=$('.hero-book');hb.innerHTML=coverMarkup(b);hb.classList.toggle('has-cover',!!b.cover);$('#heroRead').textContent=b.progress>0&&b.progress<100?'Continue reading →':'Start reading →';$('#heroRead').onclick=()=>{selected=b;openReader()}}
function enhanceDetail(){if(!selected)return;const host=$('#detail .sheet');host.querySelector('.v3-detail')?.remove();const d=document.createElement('div');d.className='v3-detail';const r=clamp(num(state.ratings[selected.id]),0,5);const custom=state.shelves[selected.id]||'';d.innerHTML=`<small>YOUR ARCHIVE RECORD</small><div class="v3-rating">${[1,2,3,4,5].map(n=>`<button data-rate="${n}" class="${n<=r?'on':''}">★</button>`).join('')}</div><textarea id="v3Note" placeholder="Private notes…">${esc(state.notes[selected.id]||'')}</textarea><input id="v3Shelf" placeholder="Custom shelf name" value="${esc(custom)}"><div class="v3-actions"><button data-status="tbr">＋ TBR</button><button data-status="reading">▶ Reading</button><button data-status="finished">✓ Finished</button><button id="v3Save">Save record</button></div>`;host.appendChild(d);$$('[data-rate]',d).forEach(b=>b.onclick=()=>{state.ratings[selected.id]=+b.dataset.rate;saveState();enhanceDetail();render()});$('#v3Save',d).onclick=()=>{state.notes[selected.id]=$('#v3Note',d).value;state.shelves[selected.id]=$('#v3Shelf',d).value.trim();saveState();render()};$$('[data-status]',d).forEach(b=>b.onclick=()=>setStatus(selected,b.dataset.status))}
function openDetail(id){selected=books.find(b=>String(b.id)===String(id));if(!selected)return;syncBookProgress(selected);$('#detailCover').innerHTML=coverMarkup(selected);$('#detailCover').classList.toggle('has-cover',!!selected.cover);$('#detailFandom').textContent=selected.fandom||selected.genre||'Original';$('#detailTitle').textContent=selected.title;$('#detailAuthor').textContent='by '+(selected.author||'Unknown');$('#tags').innerHTML=arr(selected.tags).map(t=>`<span>${esc(t)}</span>`).join('');$('#summary').textContent=selected.summary||'';$('#words').textContent=(selected.words||0).toLocaleString()+' words';$('#chapters').textContent=arr(selected.chapters).length+' chapters';$('#status').textContent=`${selected.status||''}${selected.progress?` · ${selected.progress}% read`:''}`;$('#favBtn').textContent=selected.favorite?'♥ Favorited':'♡ Add to favorites';$('#readBtn').textContent=selected.progress>0&&selected.progress<100?'CONTINUE READING':'READ NOW';$('#detail').classList.remove('hidden');requestAnimationFrame(enhanceDetail)}
function setStatus(b,mode){if(mode==='tbr'&&(b.progress||0)>0&&!confirm('Move this back to TBR and reset progress?'))return;if(mode==='tbr'){delete readingData.books[b.id];delete readingData.opened[b.id];b.progress=0;b.lastChapter=0;b.shelf='tbr'}else if(mode==='reading'){readingData.opened[b.id]=true;b.shelf='reading'}else if(mode==='finished'){readingData.opened[b.id]=true;const t=trackerFor(b);b.chapters.forEach((_,i)=>t.chapters[i]=1);b.shelf='finished';b.progress=100;b.lastChapter=Math.max(0,b.chapters.length-1)}saveReadingData();persist();render();openDetail(b.id)}
let lastReaderActivity=0,readerSecondsSinceOpen=0,readTick=0;
function activity(){lastReaderActivity=Date.now()}
['touchstart','pointerdown','keydown','scroll'].forEach(e=>readerEl.addEventListener(e,activity,{passive:true}));
function recordPosition(force=false){if(!selected||readerEl.classList.contains('hidden'))return;const text=$('#chapterText');if(!text)return;const t=trackerFor(selected);let f=force?1:0; if(!force){const rect=text.getBoundingClientRect();const total=Math.max(1,text.scrollHeight);const passed=clamp(-rect.top+readerEl.clientHeight*.5,0,total);f=clamp(passed/total,0,1);if(f>.985)f=1}t.chapters[chapter]=Math.max(num(t.chapters[chapter]),f);readingData.opened[selected.id]=true;selected.lastChapter=chapter;syncBookProgress(selected);saveReadingData();persist();updateStats()}
function applyReader(){readerEl.classList.remove('v3-sepia','v3-midnight','v3-sans','v3-serif','v3-garamond','dark');if(state.prefs.theme==='sepia')readerEl.classList.add('v3-sepia');if(state.prefs.theme==='midnight')readerEl.classList.add('v3-midnight');readerEl.classList.add(`v3-${state.prefs.font}`);$('#chapterText').style.fontSize=state.prefs.size+'px'}
function showChapter(){const c=selected?.chapters?.[chapter];if(!c)return;$('#readerTitle').textContent=selected.title;$('#readerChapter').textContent=`CHAPTER ${chapter+1} OF ${selected.chapters.length}`;$('#chapterTitle').textContent=c[0];$('#chapterText').innerHTML=String(c[1]||'').split(/\n\s*\n/).filter(Boolean).map(p=>`<p>${esc(p).replace(/\n/g,'<br>')}</p>`).join('');$('#prevChapter').disabled=chapter===0;$('#nextChapter').textContent=chapter===selected.chapters.length-1?'Finish ✓':'Next →';$('#progress').textContent=`${selected.progress||0}% book`;selected.lastChapter=chapter;persist();readerEl.scrollTop=0;applyReader();syncBookmarkButton();activity()}
function openReader(){if(!selected||!selected.chapters?.length)return;readingData.opened[selected.id]=true;chapter=clamp(num(selected.lastChapter),0,selected.chapters.length-1);selected.shelf='reading';state.history.unshift({id:selected.id,at:Date.now(),chapter});state.history=state.history.slice(0,200);saveState();saveReadingData();showChapter();readerEl.classList.remove('hidden');$('#detail').classList.add('hidden');readerSecondsSinceOpen=0;activity();persist();render();setupFeatured()}
setInterval(()=>{if(readerEl.classList.contains('hidden')||document.hidden)return;if(Date.now()-lastReaderActivity>90000)return;readingData.seconds++;readerSecondsSinceOpen++;readTick++;if(readerSecondsSinceOpen>=20)markToday();if(readTick>=5){readTick=0;saveReadingData();updateStats();refreshDashboard()}},1000);
readerEl.addEventListener('scroll',()=>{clearTimeout(readerEl._v3scroll);readerEl._v3scroll=setTimeout(()=>recordPosition(false),180)},{passive:true});
function closeOverlay(sel){$(sel)?.classList.add('hidden');document.body.classList.remove('v3-modal-open')}
$('#closeDetail').onclick=()=>closeOverlay('#detail');$('#detail').onclick=e=>{if(e.target.id==='detail')closeOverlay('#detail')};$('#readBtn').onclick=openReader;$('#favBtn').onclick=()=>{if(!selected)return;selected.favorite=!selected.favorite;persist();openDetail(selected.id);render()};
$('#readerBack').onclick=()=>{recordPosition(false);readerEl.classList.add('hidden');render();setupFeatured()};$('#prevChapter').onclick=()=>{recordPosition(false);if(chapter>0){chapter--;showChapter()}};$('#nextChapter').onclick=()=>{recordPosition(true);if(chapter<selected.chapters.length-1){chapter++;showChapter();render()}else{selected.shelf='finished';persist();render();setupFeatured();readerEl.classList.add('hidden')}};
function ensureReaderTools(){let o=$('#v3ReaderTools');if(o)return o;o=document.createElement('div');o.id='v3ReaderTools';o.className='overlay hidden v3-tools-overlay';o.innerHTML=`<article class="sheet"><button class="close" data-close>×</button><small>THE ARCHIVE READER</small><h2>Reader settings</h2><div class="v3-chiprow"><button data-theme="paper">Paper</button><button data-theme="sepia">Sepia</button><button data-theme="midnight">Midnight</button></div><div class="v3-chiprow"><button data-font="serif">Classic</button><button data-font="garamond">Garamond</button><button data-font="sans">Clean</button></div><div class="v3-chiprow"><button id="v3Smaller">A−</button><button id="v3Larger">A＋</button><button id="v3Bookmark">Bookmark</button><button id="v3Quote">Save quote</button></div><select id="v3Jump"></select><div id="v3Bookmarks"></div></article>`;document.body.appendChild(o);$('[data-close]',o).onclick=()=>o.classList.add('hidden');o.onclick=e=>{if(e.target===o)o.classList.add('hidden')};$$('[data-theme]',o).forEach(b=>b.onclick=()=>{state.prefs.theme=b.dataset.theme;saveState();applyReader();syncReaderTools()});$$('[data-font]',o).forEach(b=>b.onclick=()=>{state.prefs.font=b.dataset.font;saveState();applyReader();syncReaderTools()});$('#v3Smaller',o).onclick=()=>{state.prefs.size=clamp(state.prefs.size-1,15,27);saveState();applyReader()};$('#v3Larger',o).onclick=()=>{state.prefs.size=clamp(state.prefs.size+1,15,27);saveState();applyReader()};$('#v3Bookmark',o).onclick=addBookmark;$('#v3Quote',o).onclick=saveQuote;$('#v3Jump',o).onchange=e=>{recordPosition(false);chapter=+e.target.value;showChapter();o.classList.add('hidden')};return o}
function addBookmark(){if(!selected)return;const list=arr(state.bookmarks[selected.id]);const t=trackerFor(selected);const fraction=clamp(num(t.chapters[chapter]),0,1);list.unshift({chapter,fraction,at:Date.now()});state.bookmarks[selected.id]=list.slice(0,100);saveState();syncReaderTools();syncBookmarkButton()}
function syncBookmarkButton(){const b=$('#readerTheme');if(b)b.dataset.bookmarked=arr(state.bookmarks[selected?.id]).some(x=>x.chapter===chapter)?'1':'0'}
function saveQuote(){if(!selected)return;let s=String(window.getSelection()?.toString()||'').trim();if(!s)return alert('Select a line first ♡');if(s.length>600)s=s.slice(0,600)+'…';if(!state.quotes.some(q=>q.id===selected.id&&q.chapter===chapter&&q.text===s))state.quotes.unshift({id:selected.id,title:selected.title,chapter,text:s,at:Date.now()});state.quotes=state.quotes.slice(0,200);saveState()}
function syncReaderTools(){const o=ensureReaderTools();$$('[data-theme]',o).forEach(b=>b.classList.toggle('active',b.dataset.theme===state.prefs.theme));$$('[data-font]',o).forEach(b=>b.classList.toggle('active',b.dataset.font===state.prefs.font));if(selected){$('#v3Jump',o).innerHTML=selected.chapters.map((c,i)=>`<option value="${i}" ${i===chapter?'selected':''}>${i+1}. ${esc(c[0])}</option>`).join('');const marks=arr(state.bookmarks[selected.id]);$('#v3Bookmarks',o).innerHTML=marks.length?`<h3>Bookmarks</h3>${marks.map((m,i)=>`<button class="v3-bookmark-row" data-bm="${i}">Chapter ${m.chapter+1} · ${Math.round((m.fraction||0)*100)}%</button>`).join('')}`:'';$$('[data-bm]',o).forEach(b=>b.onclick=()=>{const m=marks[+b.dataset.bm];chapter=m.chapter;showChapter();o.classList.add('hidden')})}}
$('#readerTheme').onclick=()=>{syncReaderTools();ensureReaderTools().classList.remove('hidden')};
function ensureFilterUI(){if($('#v3Genres'))return;const tools=$('.tools');const genres=document.createElement('div');genres.id='v3Genres';genres.className='archive-genres';genres.innerHTML=Object.keys(GENRES).map(g=>`<button data-genre="${g}">${g}</button>`).join('');tools.parentNode.insertBefore(genres,tools);genres.onclick=e=>{const b=e.target.closest('[data-genre]');if(!b)return;state.genre=b.dataset.genre;saveState();syncFilterUI();render()};const f=document.createElement('button');f.id='v3FilterBtn';f.textContent='☷';f.setAttribute('aria-label','Filter and sort');tools.appendChild(f);f.onclick=openFilter;syncFilterUI()}
function syncFilterUI(){$$('#v3Genres [data-genre]').forEach(b=>b.classList.toggle('active',b.dataset.genre===state.genre))}
function openFilter(){let o=$('#v3Filter');if(!o){o=document.createElement('div');o.id='v3Filter';o.className='overlay hidden';o.innerHTML=`<article class="sheet"><button class="close" data-close>×</button><small>FILTER & SORT</small><h2>Shape the shelf</h2><div class="v3-chiprow" id="v3Sort">${[['default','Default'],['title','A–Z'],['short','Shortest'],['long','Longest'],['progress','Progress'],['rating','My rating']].map(([v,l])=>`<button data-sort="${v}">${l}</button>`).join('')}</div><div class="v3-chiprow"><button id="v3Unread">Unread only</button><button data-min="0">Any length</button><button data-min="20000">20k+</button><button data-min="40000">40k+</button></div></article>`;document.body.appendChild(o);$('[data-close]',o).onclick=()=>o.classList.add('hidden');o.onclick=e=>{if(e.target===o)o.classList.add('hidden');const s=e.target.dataset.sort;if(s){state.sort=s;saveState();render();syncFilterSheet()}if(e.target.dataset.min!==undefined){state.minWords=+e.target.dataset.min;saveState();render();syncFilterSheet()}if(e.target.id==='v3Unread'){state.unread=!state.unread;saveState();render();syncFilterSheet()}}}syncFilterSheet();o.classList.remove('hidden')}
function syncFilterSheet(){const o=$('#v3Filter');if(!o)return;$$('[data-sort]',o).forEach(b=>b.classList.toggle('active',b.dataset.sort===state.sort));$('#v3Unread',o).classList.toggle('active',state.unread);$$('[data-min]',o).forEach(b=>b.classList.toggle('active',+b.dataset.min===state.minWords))}
function ensureCollectionsButton(){const nav=$('nav');if(nav.querySelector('[data-collections2]'))return;const b=document.createElement('button');b.dataset.collections2='1';b.textContent='Collections';b.onclick=openCollections;nav.appendChild(b)}
function openCollections(){let o=$('#v3Collections');if(!o){o=document.createElement('div');o.id='v3Collections';o.className='overlay hidden';o.innerHTML='<article class="sheet"><button class="close" data-close>×</button><small>COLLECTIONS</small><h2>Every door in one place.</h2><div data-body></div></article>';document.body.appendChild(o);$('[data-close]',o).onclick=()=>o.classList.add('hidden');o.onclick=e=>{if(e.target===o)o.classList.add('hidden')}}const defs=[['Reading now',b=>b.shelf==='reading'],['TBR',b=>b.shelf==='tbr'],['Favorites',b=>b.favorite],['Horror',GENRES.Horror],['Dark Romance',GENRES['Dark Romance']],['Fantasy',GENRES.Fantasy],['Vampires',GENRES.Vampires],['Fanfiction',GENRES.Fanfic],['Finished',b=>b.progress>=100]];const body=$('[data-body]',o);body.innerHTML=defs.map(([n,fn])=>{const a=books.filter(fn);return`<section class="v3-collection"><h3>${esc(n)}</h3><small>${a.length} books</small><div class="v3-collection-grid">${a.slice(0,20).map(b=>`<button data-book="${esc(b.id)}">${esc(b.title)}<span>${esc(b.author||'')}</span></button>`).join('')||'<em>Empty for now.</em>'}</div></section>`}).join('');$$('[data-book]',body).forEach(b=>b.onclick=()=>{o.classList.add('hidden');openDetail(b.dataset.book)});o.classList.remove('hidden')}
function dashboard(){if($('#v3Dashboard'))return;const s=$('.stats');const d=document.createElement('section');d.id='v3Dashboard';d.className='v3-dashboard';d.innerHTML=`<div class="v3-panel"><small>READING RITUAL</small><h2>Tonight belongs to a book.</h2><div id="v3Week" class="v3-week"></div></div><div class="v3-panel"><small>THE ARCHIVE KNOWS</small><div class="v3-statgrid"><div><b id="v3Streak">0</b><span>day streak</span></div><div><b id="v3Words">0</b><span>words read</span></div><div><b id="v3Minutes">0m</b><span>reading time</span></div></div><div class="v3-goal"><i id="v3Goal"></i></div><small id="v3GoalText"></small></div>`;s.parentNode.insertBefore(d,s);refreshDashboard()}
function refreshDashboard(){if(!$('#v3Dashboard'))return;const ds=new Set(readingDays()),today=new Date(),week=[];for(let i=6;i>=0;i--){const d=new Date(today);d.setDate(today.getDate()-i);week.push(`<div class="v3-day ${ds.has(dayKey(d))?'read':''}">${d.toLocaleDateString(undefined,{weekday:'short'}).slice(0,2)}<b>${d.getDate()}</b></div>`)}$('#v3Week').innerHTML=week.join('');$('#v3Streak').textContent=streak();const words=totalWordsRead();$('#v3Words').textContent=words.toLocaleString();$('#v3Minutes').textContent=formatTime(readingData.seconds);$('#v3Goal').style.width=Math.min(100,words/state.goal*100)+'%';$('#v3GoalText').textContent=`${words.toLocaleString()} / ${state.goal.toLocaleString()} words`}
function cleanupBookState(id){delete readingData.books[id];delete readingData.opened[id];delete state.ratings[id];delete state.notes[id];delete state.shelves[id];delete state.bookmarks[id];state.history=state.history.filter(h=>String(h.id)!==String(id));state.quotes=state.quotes.filter(q=>String(q.id)!==String(id));saveReadingData();saveState();persist()}
window.cleanupBookState=cleanupBookState;
window.openCollections=openCollections;
window.renderMega=renderMega;
window.ArchiveApp={render,openDetail,openCollections,cleanupBookState,get books(){return books}};
document.querySelectorAll('nav button[data-filter]').forEach(b=>b.onclick=()=>{document.querySelectorAll('nav button[data-filter]').forEach(x=>x.classList.toggle('active',x===b));filter=b.dataset.filter;render()});
$('#search').oninput=render;
$('#profile').onclick=()=>$('#profileSheet').classList.remove('hidden');$('#closeProfile').onclick=()=>closeOverlay('#profileSheet');
document.addEventListener('visibilitychange',()=>{recordPosition(false);saveReadingData()});window.addEventListener('pagehide',()=>{recordPosition(false);saveReadingData();saveState()});
async function hydrateLibrarianBooks(){const meta=safeJSON('archive-librarian-books-v2',[]);if(!Array.isArray(meta)||!window.ArchiveLibrarian)return}
(async function init(){const featured=await Promise.all([loadFanfic(),loadOfficialBook()]);const built=getAllBuiltIns();const saved=savedState();const custom=saved.filter(b=>b&&typeof b==='object'&&!featured.concat(built).some(x=>String(x.id)===String(b.id))&&!b.librarianV2);books=[...mergeSaved(featured.concat(built)),...custom];books.forEach(b=>{b.tags=arr(b.tags);b.chapters=arr(b.chapters);b.words=actualWords(b)||num(b.words);if(!b.shelf)b.shelf='tbr'});persist();ensureFilterUI();ensureCollectionsButton();dashboard();render();setupFeatured();console.info('The Archive 3.0 loaded:',books.length,'books')})();