const demos=[
{id:'velvet',title:'Velvet & Venom',author:'M. Vale',fandom:'Original',tags:['Dark romance','Slow burn','Enemies to lovers'],summary:'Two people with excellent reasons to stay away from each other make the deeply inconvenient decision not to.',words:68400,status:'Complete',shelf:'reading',favorite:true,progress:42,chapters:[['The Invitation',`The envelope arrived without a stamp, sealed in wine-red wax. Mara turned it over twice before breaking the seal.\n\nThere were invitations one accepted because they were polite, and invitations one accepted because refusing felt considerably more dangerous. This was unmistakably the second kind.`],['The House',`Inside, the house seemed to breathe around its guests. Music drifted from somewhere beyond the staircase, low and distant.`]]},
{id:'ashes',title:'Ashes in Bloom',author:'C. Rowan',fandom:'Original',tags:['Gothic','Mystery','Found family'],summary:'A ruined greenhouse, a house full of secrets, and flowers that refuse to stay dead.',words:51200,status:'Complete',shelf:'tbr',favorite:false,progress:0,chapters:[['The Greenhouse',`By spring, everyone in the village had agreed the greenhouse was empty. Everyone except June.`]]},
{id:'orbit',title:'Orbiting You',author:'L. Hart',fandom:'Sci-Fi',tags:['Friends to lovers','Space','Longing'],summary:'Some distances are measured in light-years. Others are measured in all the things you never said.',words:89300,status:'Complete',shelf:'reading',favorite:false,progress:18,chapters:[['Departure',`Earth became a blue coin beneath them, then a marble, then something too small to hold all the people they had left behind.`]]},
{id:'thorns',title:'A Crown of Thorns',author:'A. Nocturne',fandom:'Fantasy',tags:['Royalty','Forbidden love','Magic'],summary:'The crown chooses its ruler. Unfortunately, it has terrible taste in romance.',words:104000,status:'Complete',shelf:'finished',favorite:true,progress:100,chapters:[['Coronation',`The crown drew blood before it gave her power. Elara considered that an honest introduction.`]]},
{id:'rain',title:'When It Rains',author:'S. Grey',fandom:'Original',tags:['Cozy','Romance','Rainy day'],summary:'A tiny bookshop, terrible weather, and the same stranger arriving every Thursday.',words:32700,status:'Complete',shelf:'tbr',favorite:false,progress:0,chapters:[['Thursday',`It rained every Thursday that October.`]]}
];
const OFFICIAL_ID='door-radiator',MANUSCRIPT='The door behind the radiator .txt',COVER='thedoorbehindtheradiator.PNG';
const FANFIC_ID='veil-of-forks',FANFIC_MANUSCRIPT='twilight-dark-fanfic.txt',FANFIC_COVER='veil-of-forks-cover.svg';
const LIBRARY_KEY='archive-books',READING_KEY='archive-reading-stats-v1';
const $=s=>document.querySelector(s),shelf=$('#shelf'),readerEl=$('#reader');
let filter='all',selected=null,chapter=0,books=[],secondTick=0;
function savedState(){try{return JSON.parse(localStorage.getItem(LIBRARY_KEY)||'[]')}catch{return[]}}
function persist(){localStorage.setItem(LIBRARY_KEY,JSON.stringify(books))}
function getReadingData(){try{return JSON.parse(localStorage.getItem(READING_KEY))||{seconds:0,opened:{},books:{}}}catch{return{seconds:0,opened:{},books:{}}}}
let readingData=getReadingData();
function saveReadingData(){localStorage.setItem(READING_KEY,JSON.stringify(readingData))}
function escapeHTML(v=''){return v.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]))}
function wc(s){return s&&s.trim()?s.trim().split(/\s+/).length:0}
function parseManuscript(raw){const clean=raw.replace(/\r/g,'').replace(/\u2028|\u2029/g,'\n'),heading=/^(Chapter\s+\d+\s*[–—-]\s*.+|Extra\s*[–—-]\s*.+)$/gmi,matches=[...clean.matchAll(heading)];return matches.map((m,i)=>[m[0].trim(),clean.slice(m.index+m[0].length,i+1<matches.length?matches[i+1].index:clean.length).trim()]).filter(c=>c[1])}
function parseFanfic(raw){const clean=raw.replace(/\r/g,''),heading=/^(CHAPTER\s+\d+\s*[–—-]\s*.+|EPILOGUE\s*[–—-]\s*.+)$/gm,matches=[...clean.matchAll(heading)];return matches.map((m,i)=>[m[0].replace(/^CHAPTER\s+\d+\s*[–—-]\s*/,'').replace(/^EPILOGUE\s*[–—-]\s*/,'Epilogue — '),clean.slice(m.index+m[0].length,i+1<matches.length?matches[i+1].index:clean.length).trim()]).filter(c=>c[1])}
async function loadText(path){try{const r=await fetch(encodeURI(path),{cache:'no-store'});if(!r.ok)throw 0;return await r.text()}catch(e){console.error('Could not load',path);return''}}
async function loadOfficialBook(){const text=await loadText(MANUSCRIPT),chapters=parseManuscript(text);return{id:OFFICIAL_ID,title:'The Door Behind the Radiator',author:'Marie Dudek',fandom:'Original Horror',tags:['Psychological horror','Other world','Winter','Uncanny','Dark fantasy'],summary:'Fifteen-year-old Michael Petrov hears something whispering through the radiator in his Saint Petersburg apartment. Behind it waits a tiny door, an impossible copy of home, and a world offering warmth, safety and love at a price he cannot afford to pay.',tagline:'Some doors are meant to stay closed.',words:chapters.reduce((n,c)=>n+wc(c[1]),0),status:'Complete',shelf:'tbr',favorite:false,progress:0,lastChapter:0,cover:COVER,official:true,chapters:chapters.length?chapters:[['Manuscript unavailable','Please refresh the page.']]}}
async function loadFanfic(){const text=await loadText(FANFIC_MANUSCRIPT);let chapters=parseFanfic(text);if(typeof window.expandVeilChapters==='function')chapters=window.expandVeilChapters(chapters);const actualWords=chapters.reduce((n,ch)=>n+wc(ch[1]),0);return{id:FANFIC_ID,title:'Veil of Forks',author:'Elias',fandom:'Twilight · Alternate Universe',tags:['Edward Cullen','Marie','Obsessive Edward','Slow burn','Vampires','Forks','Alternate universe'],summary:'Bella Swan never came to Forks. Marie did. Edward Cullen cannot hear her thoughts, cannot understand why she does not care about him, and becomes increasingly obsessed with the one person who refuses to orbit him.',tagline:'He can hear everyone except the girl he cannot stop watching.',words:actualWords,status:`Complete · 40 chapters · ${actualWords.toLocaleString()} words`,shelf:'tbr',favorite:false,progress:0,lastChapter:0,cover:FANFIC_COVER,official:true,fanfic:true,chapters:chapters.length?chapters:[['Story unavailable','Please refresh the page.']]}}
function mergeLibrary(featured){const saved=savedState(),officialIds=[OFFICIAL_ID,FANFIC_ID];const official=featured.map(b=>{const p=saved.find(x=>x.id===b.id);return p?{...b,shelf:p.shelf,favorite:p.favorite,progress:p.progress||0,lastChapter:p.lastChapter||0}:b});const custom=saved.filter(b=>!demos.some(d=>d.id===b.id)&&!officialIds.includes(b.id));const demoMerged=demos.map(d=>{const p=saved.find(b=>b.id===d.id);return p?{...d,shelf:p.shelf,favorite:p.favorite,progress:p.progress||0,lastChapter:p.lastChapter||0}:d});books=[...official,...demoMerged,...custom];bootstrapLegacyReading();syncAllProgress();persist();saveReadingData()}
function trackerFor(book){if(!readingData.books[book.id])readingData.books[book.id]={chapters:{}};return readingData.books[book.id]}
function bootstrapLegacyReading(){books.forEach(book=>{if(!book.progress||readingData.books[book.id])return;readingData.opened[book.id]=true;const t=trackerFor(book);let remaining=(book.progress/100)*(book.words||book.chapters.reduce((n,c)=>n+wc(c[1]),0));book.chapters.forEach((c,i)=>{if(remaining<=0)return;const n=wc(c[1]);const f=Math.min(1,remaining/Math.max(1,n));t.chapters[i]=f;remaining-=n*f})})}
function wordsReadFor(book){const t=readingData.books[book.id];if(!t)return 0;return Math.min(book.words||Infinity,book.chapters.reduce((sum,c,i)=>sum+Math.round(wc(c[1])*Math.min(1,t.chapters[i]||0)),0))}
function syncBookProgress(book){const total=book.words||book.chapters.reduce((n,c)=>n+wc(c[1]),0)||1;book.progress=Math.min(100,Math.round(wordsReadFor(book)/total*100));if(book.progress>=100)book.shelf='finished';else if(readingData.opened[book.id])book.shelf='reading'}
function syncAllProgress(){books.forEach(syncBookProgress)}
function chapterCountRead(){return books.reduce((total,b)=>{const t=readingData.books[b.id];if(!t)return total;return total+Object.values(t.chapters||{}).filter(v=>v>=.985).length},0)}
function totalWordsRead(){return books.reduce((n,b)=>n+wordsReadFor(b),0)}
function formatTime(seconds){const mins=Math.floor(seconds/60);if(mins<60)return `${mins}m`;const h=Math.floor(mins/60),m=mins%60;return `${h}h ${String(m).padStart(2,'0')}m`}
function updateStats(){const a=$('#booksOpenedCount'),b=$('#chaptersReadCount'),c=$('#readingTime'),d=$('#wordCount');if(a)a.textContent=Object.keys(readingData.opened).length;if(b)b.textContent=chapterCountRead().toLocaleString();if(c)c.textContent=formatTime(readingData.seconds||0);if(d)d.textContent=totalWordsRead().toLocaleString()}
function offsetInside(el,ancestor){let y=0,node=el;while(node&&node!==ancestor){y+=node.offsetTop||0;node=node.offsetParent}return y}
function recordPosition(forceComplete=false){if(!selected||readerEl.classList.contains('hidden'))return;const text=$('#chapterText'),t=trackerFor(selected);let fraction=1;if(!forceComplete){const top=offsetInside(text,readerEl),line=readerEl.scrollTop+readerEl.clientHeight*.72;fraction=Math.max(0,Math.min(1,(line-top)/Math.max(1,text.scrollHeight)));if(fraction>.985)fraction=1}t.chapters[chapter]=Math.max(t.chapters[chapter]||0,fraction);readingData.opened[selected.id]=true;syncBookProgress(selected);selected.lastChapter=chapter;saveReadingData();persist();updateStats();setupFeatured()}
function coverMarkup(b,detail=false){return b.cover?`<img class="real-cover${detail?' detail-image':''}" src="${b.cover}" alt="Cover of ${escapeHTML(b.title)}">`:`<span>${escapeHTML(b.title)}</span><i>${b.favorite?'♡':'✦'}</i>`}
function render(){syncAllProgress();const q=$('#search').value.toLowerCase(),list=books.filter(b=>(filter==='all'||(filter==='favorite'?b.favorite:b.shelf===filter))&&`${b.title} ${b.author} ${b.fandom} ${b.tags.join(' ')}`.toLowerCase().includes(q));shelf.innerHTML=list.map(b=>`<div class="book-card ${b.official?'official-book':''}" data-id="${b.id}"><div class="book">${coverMarkup(b)}</div><b>${escapeHTML(b.title)}</b><small>${escapeHTML(b.author)}</small><div class="progressbar"><i style="width:${b.progress||0}%"></i></div></div>`).join('');$('#count').textContent=`${list.length} titles`;updateStats();document.querySelectorAll('.book-card').forEach(x=>x.onclick=()=>openDetail(x.dataset.id))}
function setupFeatured(){const b=books.find(x=>x.id===FANFIC_ID)||books.find(x=>x.id===OFFICIAL_ID);if(!b)return;$('#heroTitle').textContent=b.title;const p=document.querySelector('.hero-copy p');if(p)p.textContent=b.fanfic?`Twilight AU · obsessive slow burn · ${b.words.toLocaleString()} words`:'Psychological horror · dark fantasy · complete';const hb=document.querySelector('.hero-book');if(hb){hb.innerHTML=`<img class="real-cover" src="${b.cover}" alt="${escapeHTML(b.title)} cover">`;hb.classList.add('has-cover')}$('#heroRead').textContent=b.progress>0?'Continue reading →':'Start reading →'}
function openDetail(id){selected=books.find(b=>b.id===id);if(!selected)return;syncBookProgress(selected);$('#detailCover').innerHTML=coverMarkup(selected,true);$('#detailCover').classList.toggle('has-cover',!!selected.cover);$('#detailFandom').textContent=selected.fandom;$('#detailTitle').textContent=selected.title;$('#detailAuthor').textContent='by '+selected.author;$('#tags').innerHTML=selected.tags.map(t=>`<span>${escapeHTML(t)}</span>`).join('');$('#summary').textContent=selected.summary;$('#words').textContent=(selected.words||0).toLocaleString()+' words';$('#chapters').textContent=selected.chapters.length+' chapters';$('#status').textContent=selected.progress?`${selected.status} · ${selected.progress}% read`:selected.status;$('#favBtn').textContent=selected.favorite?'♥ Favorited':'♡ Add to favorites';$('#readBtn').textContent=selected.progress>0&&selected.progress<100?'CONTINUE READING':'READ NOW';$('#detail').classList.remove('hidden')}
function close(x){$(x).classList.add('hidden')}
function openReader(){if(!selected)return;readingData.opened[selected.id]=true;chapter=Math.min(selected.lastChapter||0,selected.chapters.length-1);selected.shelf='reading';saveReadingData();showChapter();readerEl.classList.remove('hidden');$('#detail').classList.add('hidden');requestAnimationFrame(()=>recordPosition(false));persist();render();setupFeatured()}
function showChapter(){const c=selected.chapters[chapter];$('#readerTitle').textContent=selected.title;$('#readerChapter').textContent=`CHAPTER ${chapter+1} OF ${selected.chapters.length}`;$('#chapterTitle').textContent=c[0];$('#chapterText').innerHTML=c[1].split(/\n\s*\n/).filter(Boolean).map(p=>`<p>${escapeHTML(p).replace(/\n/g,'<br>')}</p>`).join('');$('#progress').textContent=`${selected.progress||0}% book`;$('#prevChapter').disabled=chapter===0;$('#nextChapter').textContent=chapter===selected.chapters.length-1?'Finish ✓':'Next →';selected.lastChapter=chapter;persist();readerEl.scrollTop=0}
readerEl.addEventListener('scroll',()=>{clearTimeout(readerEl._rt);readerEl._rt=setTimeout(()=>recordPosition(false),120)},{passive:true});
setInterval(()=>{if(!readerEl.classList.contains('hidden')&&!document.hidden){readingData.seconds=(readingData.seconds||0)+1;secondTick++;if(secondTick>=5){secondTick=0;saveReadingData();updateStats()}}},1000);
document.addEventListener('visibilitychange',()=>{recordPosition(false);saveReadingData()});window.addEventListener('pagehide',()=>{recordPosition(false);saveReadingData()});
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{document.querySelector('nav .active').classList.remove('active');b.classList.add('active');filter=b.dataset.filter;render()});
$('#search').oninput=render;$('#closeDetail').onclick=()=>close('#detail');$('#detail').onclick=e=>{if(e.target.id==='detail')close('#detail')};$('#readBtn').onclick=openReader;$('#heroRead').onclick=()=>{selected=books.find(b=>b.id===FANFIC_ID)||books[0];openReader()};$('#favBtn').onclick=()=>{selected.favorite=!selected.favorite;persist();openDetail(selected.id);render()};
$('#readerBack').onclick=()=>{recordPosition(false);close('#reader');render()};$('#readerTheme').onclick=()=>readerEl.classList.toggle('dark');
$('#prevChapter').onclick=()=>{recordPosition(false);if(chapter>0){chapter--;showChapter()}};
$('#nextChapter').onclick=()=>{recordPosition(true);if(chapter<selected.chapters.length-1){chapter++;showChapter();render()}else{selected.progress=100;selected.shelf='finished';persist();render();setupFeatured();close('#reader')}};
$('#addBtn').onclick=()=>$('#addSheet').classList.remove('hidden');$('#closeAdd').onclick=()=>close('#addSheet');$('#saveBook').onclick=()=>{const title=$('#newTitle').value.trim(),text=$('#newText').value.trim();if(!title||!text)return alert('Give the book a title and some text ♡');books.unshift({id:Date.now().toString(),title,author:$('#newAuthor').value||'Unknown',fandom:$('#newFandom').value||'Original',tags:$('#newTags').value.split(',').map(x=>x.trim()).filter(Boolean),summary:$('#newSummary').value||'A private addition to The Archive.',words:wc(text),status:'In progress',shelf:'tbr',favorite:false,progress:0,chapters:[['Chapter One',text]]});persist();render();close('#addSheet')};
$('#profile').onclick=()=>$('#profileSheet').classList.remove('hidden');$('#closeProfile').onclick=()=>close('#profileSheet');
(async function init(){mergeLibrary([await loadFanfic(),await loadOfficialBook()]);render();setupFeatured()})();